apiVersion: v1
kind: ConfigMap
metadata:
  name: order-api-config
data:
  HTTP_ADDR: ":8080"
  INVENTORY_SVC_ADDR: "inventory-svc:9091"
  PAYMENT_SVC_ADDR: "payment-svc:9092"
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_TOPIC: "order.placed"
