apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-worker
  template:
    metadata:
      labels:
        app: notification-worker
    spec:
      containers:
        - name: notification-worker
          image: soolame7/deepdive-notification-worker:2aa8b318a472e0309c0a5286e1978fdfee00a840
          envFrom:
            - configMapRef:
                name: notification-worker-config
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits: { memory: 128Mi }
