apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: kafbat/kafka-ui:v1.5.0
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: deepdive
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka.data.svc.cluster.local:9092
          resources:
            requests: { cpu: 50m, memory: 256Mi }
            limits: { memory: 384Mi }
          readinessProbe:
            httpGet: { path: /, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 5
